import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

const SFPro = localFont({
  src: [
    {
      path: "../../public/fonts/SF-Pro.ttf",
      style: "normal",
      weight: "400",
    },
    {
      path: "../../public/fonts/SF-Pro-Text-Medium.otf",
      style: "normal",
      weight: "500",
    },
    {
      path: "../../public/fonts/SF-Pro-Text-Bold.otf",
      style: "normal",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${SFPro.className} antialiased`}>{children}</body>
    </html>
  );
}
