import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

import Menubar from "@/components/Menubar";
import Dock from "@/components/Dock";
import WallpaperProvider from "@/providers/WallpaperProvider";

const SFPro = localFont({
  src: [
    {
      path: "../../public/fonts/SF-Pro.ttf",
      style: "normal",
      weight: "400",
    },
    {
      path: "../../public/fonts/SFProDisplay-Medium.woff2",
      style: "normal",
      weight: "500",
    },
    {
      path: "../../public/fonts/SFProDisplay-Semibold.woff2",
      style: "normal",
      weight: "600",
    },
    {
      path: "../../public/fonts/SFProDisplay-Bold1.woff2",
      style: "normal",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${SFPro.className} initial-bg antialiased`}>
        <WallpaperProvider>
          <Menubar />

          {children}

          <Dock />
        </WallpaperProvider>
      </body>
    </html>
  );
}
